### ISSUE TITLE
This was already a mod + suggestions

### ISSUE THREAD

**Issue by SmushyTaco** [FokshaWasTaken/loading-bar#2]
Hi, you probably didn't realize it but this was made a mod years ago. It's part of my [Legacy Display](https://github.com/SmushyTaco/Legacy-Display/) mod. Upon reviewing your code I would also suggest utilizing the annotations provided by MixinExtras instead of `@Redirect` to ensure mod compatibility if you choose to continue maintaining this mod into the future.

**Comment by fokshadev** [comment]
I’m sorry! I haven’t noticed at all, I found a couple of old unmaintained mods but I haven’t stumbled across yours, thanks for the suggestions!
